name: stable

on:
  push:
    branches: [ main ]
    paths:
      - '*/Dockerfile'
      - '.github/workflows/stable.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '*/Dockerfile'
      - '.github/workflows/stable.yml'

env:
  VERSION_RE: v2.6.1
  VERSION_REM: v2.6.0 
  VERSION_BARESIP: v2.6.0

jobs:
  libre:
    env:
        IMAGE_NAME: ${{ github.repository }}/libre
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        docker build libre -t libre \
            --build-arg VERSION=${{ env.VERSION_RE }} \
            --build-arg RELEASE=1

    - name: Tag and Push image
      if: github.event_name != 'pull_request'
      run: |
        docker tag libre ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_RE }}
        docker tag libre ghcr.io/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_RE }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:latest

  librem:
    env:
        IMAGE_NAME: ${{ github.repository }}/librem
    needs: [ "libre" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        docker build librem -t librem \
            --build-arg VERSION=${{ env.VERSION_REM }} \
            --build-arg IMAGE=ghcr.io/baresip/docker/libre-dev:latest \
            --build-arg RELEASE=1

    - name: Tag and Push image
      if: github.event_name != 'pull_request'
      run: |
        docker tag librem ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_REM }}
        docker tag librem ghcr.io/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_REM }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:latest

  baresip:
    env:
        IMAGE_NAME: ${{ github.repository }}/baresip
    needs: [ "librem" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        docker build baresip -t baresip \
          --build-arg VERSION=${{ env.VERSION_BARESIP }} \
          --build-arg IMAGE=ghcr.io/baresip/docker/librem-dev:latest \
          --build-arg RELEASE=1

    - name: Tag and Push image
      if: github.event_name != 'pull_request'
      run: |
        docker tag baresip ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_BARESIP }}
        docker tag baresip ghcr.io/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION_BARESIP }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
